spring:
  application:
    name: form-schema-provider
  mvc:
    throw-exception-if-no-handler-found: true
  zipkin:
    baseUrl: http://zipkin.istio-system.svc:9411
    sender:
      type: web
  sleuth:
    opentracing:
      enabled: true
    baggage:
      correlation-enabled: true
      remote-fields: x-request-id, x-access-token
      correlation-fields: x-request-id
  web:
    resources:
      add-mappings: false
  jackson:
    deserialization:
      fail-on-missing-creator-properties: true
      fail-on-null-creator-properties: true
  redis:
    password: ${REDIS_PASSWORD}
    sentinel:
      master: mymaster
      nodes:
        - ${REDIS_NODE}

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
    jmx:
      exposure:
        exclude: "*"
  endpoint:
    health:
      enabled: true
      show-details: always
      group:
        liveness:
          include: livenessState, livenessResponseCheck
        readiness:
          include: readinessState, redis
    loggers:
      enabled: true
    prometheus:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
    kafka:
      enabled: false

springdoc:
  swagger-ui:
    path: /openapi

openapi:
  request:
    headers:
      - X-Access-Token
  response:
    codes:
      get-by-id: 200, 401, 403, 500, 501
      post: 200, 400, 401, 403, 422, 500, 501

platform:
  security:
    enabled: true
    whitelist:
      - /openapi
      - /v3/api-docs/**
      - /swagger-ui/**
      - /actuator/**
  logging:
    aspect:
      enabled: false
validator:
  schema:
    location: "classpath:schema/forms-schema.json"

logbook:
  info-logging:
    enabled: true
  strategy: without-body
  exclude:
    - /v3/api-docs/**
    - /swagger-ui/**
    - /actuator/**
    - /swagger
  obfuscate:
    headers:
      - x-access-token
      - cookie
