apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.RoleBinding.type }}
metadata:
    name: {{ .Values.RoleBinding.name }}
subjects:
    - kind: ServiceAccount
      name: {{ .Values.serviceAccount.name }}
      namespace: {{ .Values.namespace }}
roleRef:
    kind: {{ .Values.Role.type }}
    name: {{ .Values.Role.name }}
    apiGroup: rbac.authorization.k8s.io